### PR TITLE
Logger Dependency Injection

### PR DESCRIPTION
**Pull request by bbatsche**
You have such lovely log statements, it'd be nice if I could get them to go somewhere useful. ;-)

Also loaded composer's autoload files when running PHPUnit.

### CODE REVIEW

**Comment by dvdoug** [comment]
Hello

Thanks for the patch.

The classes use the LoggerAwareTrait from PSR-3 which means they all support injecting a logger via `->setLogger($someLogger)` for those that want one. Does that not work for your particular use case?

**Comment by bbatsche** [comment]
Well shucks, should have paid more attention to the PSR-3 API.

Still though, that would work for logs coming from `Packer`, but since `Packer` creates it's own instance of `VolumePacker` I wouldn't be able to see any of `VolumePacker`'s log statements unless `Packer` forwarded on its own logger.

Putting the interface in the constructor also makes dependency injection a bit easier (although it's by no means impossible without it).

**Comment by dvdoug** [comment]
I'm still dubious about putting it in the constructor since to me it's not really a dependency at all (it works without one).

But I do agree the main Packer needs to forward on the logger implementation regardless of how the logger is initially passed in.

**Comment by dvdoug** [comment]
I've just released v2.0.1 which injects the logger into the child classes at runtime. You'll need to call setLogger on the main Packer object though :)

**Pull request closed without merging**
