### PR TITLE
Basic orientation optimization

### PR DESCRIPTION
**Pull request by oucil**
These additions provide basic box rotation so that the standard orientation of all boxes and items are in the same direction.  Boxes|Items are oriented when added to the packer using addItem(), or addBox(), or when added to a list.  The optimization standardizes orientation so that the longest edge is set as the depth, and then the shortest edge is set to the height (length in your taxonomy).

The additions have been made so as to remain backward compatible with existing implementations.  Each orientation method will first verify the existence of the required setter methods before attempting to continue, and will simply return the unchanged cuboid in it's original form when they do not exist.

### CODE REVIEW

**Comment by dvdoug** [comment]
Closing until the test failures can be addressed. But thanks :)

**Comment by p4dpaul** [comment]
@oucil are you likely to do those unit tests?

**Comment by oucil** [comment]
@p4dpaul Not in the near future anyway, I've had them in use in my system since I created the PR and haven't had any problems, and I'm pretty deep in it elsewhere right now.  When I've got some extra hands around here, I'd put them on it, but it'll be a while as it stands.

**Comment by anjalirana** [comment]
Is there any way we can just check if a single or list of items will fit into provided box and return true false based on that?

**Pull request closed without merging**
